"""create blog table

Revision ID: 586809b93e6a
Revises: a5eb0cbf007e
Create Date: 2024-01-11 17:49:37.376222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586809b93e6a'
down_revision: Union[str, None] = 'a5eb0cbf007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
